apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: cv1-ambulance-wl
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/cv1-ambulance-ufe

components:
- ../../../components/version-release