apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ../../../infrastructure/polyfea
- ../../../infrastructure/fluxcd
- ../../../infrastructure/envoy-gateway
- ../../../infrastructure/observability

components:
- ../../../components/version-developers

configMapGenerator:
  - name: otel-params  
    namespace: wac-hospital 
    options:
      disableNameSuffixHash: true
    literals:
    # for development purposes we use always_on sampler, 
    # in production you may want to use parentbased_trace_id_ratio_sampler
    # or parentbased_always_on_sampler
      - OTEL_TRACES_SAMPLER=always_on
      - LOG_LEVEL=debug