apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv1-ambulance-ufe-content
spec:
  microFrontend: cv1-ambulance-ufe
  element: cv1-ambulance-wl-app
  attributes:
    - name: base-path
      value: /cv1-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv1-ambulance-wl(/.*)?$"